dequeue/dequeue.go
enqueue/enqueue.go
queue/subscription.go

This commit does some cleanup to keep the ignest library generic and
abstrcted from a particular API.

*: cleanup old references

---

README.md
dequeue/dequeue.go
dequeue/dequeue_test.go
ingest.go
mocks/Client.go

This commit adds a new `CleanUp` method to the `Client` to optionally
remove objects from the source API after they have been ingested. It
also adds a new argument to the dequeuer constructor to control the
optional clean up behavior.

ingest.go: add CleanUp method to client

---

.github/workflows/ci.yml
Makefile
README.md
go.mod
go.sum
tools.go

Currently, maintaining the README is tedious because the developer must
copy interface definitions into Markdown. This commit simplifies the
workflow of making changes to the interfaces by allowing the README to
be automatically generated. It also adds a test to assert that the
documentation is up-to-date.

Makefile: auto-generate README

---

dequeue/dequeue.go
dequeue/dequeue_test.go

Currently, the CleanUp method is only executed if an object was
_neither_ synced _nor_ marked. This is problematic, because it means
that objects that are already correctly stored will not be cleaned up,
even though they should not be re-processed. This commit fixes the logic
for the cleanup while also simplifying the function to make the logic
easier to follow, e.g. now, the code only ever has to call `mark` in one
place.

dequeue: always clean up

---

cmd/cmd.go

This commit modifies the ingest library so that the enqueuer syncs
immediately and then waits, rather than waiting _interval_ before the
first sync.

cmd: don't wait interval before syncing

---

Makefile
dequeue/dequeue_test.go
enqueue/enqueue_test.go
mocks/Nexter.go

Currently, no Go files are linted because there is no GO_PKGS variable
in Make. This commit adds this variable, triggering real linting, and
also renames a struct field about which golint was complaining.

enhancement: actually lint

---

dequeue/dequeue.go
dequeue/dequeue_test.go

This commit modifies the ingest library so that done files are only used
if a meta prefix is supplied. Otherwise, only the presence of the actual
object in question will be used to determine if it has been synced.

dequeue: conditionally use done files

---

dequeue/dequeue.go

This commit cleans up the dequeuer constructor by removing fields that
are no longer needed since they've been moved to the storage
abstraction.

dequeue: remove unused fields

---

dequeue/dequeue.go
dequeue/dequeue_test.go
mocks/storage.go
storage/s3/s3.go
storage/s3/s3_test.go
storage/storage.go

This commit adds a Stat method to the storage.Storage interface. This
allows the dequeuer to check if files need to be uploaded before doing
so. Currently the s3 storage performs this check internally, avoiding
extra uploads, however moving this to the dequeuer would allow all
storages to benefit from this functionality without needing to implement
the check themselves.
Unfortunately for the s3 storage, using done files complicates this
flow. There are two options:
1. Perform all of the stats again inside of the Store method to check
what needs to be created. This means that in the worst case, a
single upload can result in 4 stat calls, instead of the previous 2;
or
2. Allow creating meta objects in the Stat method if the object exists
but the meta object does not.
This commit takes the …

storage: move stat to storage

---

dequeue/dequeue.go

This will put to many jobs into zieb work queue.

Webkook: stop calling Webkook with empty payload

---

enqueue/enqueue.go
enqueue/enqueue_test.go

- lint
- check count
Also increase the metric if Nexter.Reset() fails.

enqueue/*: test metrics:

---

cmd/ingest/main.go
cmd/ingest/main_test.go
config/config.go
config/duration.go
enqueue/enqueue.go

cmd: create a consumer for each destination
Previsouly, ingest would reuse consumers for every destination, making
use of the multi-storage to store dequeued elements in multiple
destinations. This may make it harder to debug issues with storages and
cause unnecessary stats against successful storages. This PR changes the
logic so that every destination has its own consumer.
Note: the ingest stream _must_ use the interest retention policy to be
compatible with these consumers.
config: correctly unmarshal batch size
This commit modifies the type of the `batchSize` field of the
configuration so that `time.Duration`-style strings are correctly
unmarshaled into durations. Previously, only integers would be
unmarshaled into nanoseconds.

Don't Reuse Consumers

---

dequeue/dequeue.go

Improve logging around subscribing to a stream. In case of a non existing
stream in NATS, the logged error would be "context canceled" which is
not very helpful.

dequeue/dequeue.go: improve logging

---

cmd/ingest/main.go

This commit sets the default path for the ingest configuration YAML file
to ~/.config/ingest/config

cmd/ingest: fix default config path

---

.github/workflows/ci.yml
cmd/ingest/main.go
cmd/ingest/main_test.go
test/config.yaml

When this flag is set ingest will only load the configurations and
plugins and exit. This is helpful to make sure that all plugins can be
loaded and the configurations is valid.

cmd/ingest/main.go: add dry-run flag

---

dequeue/dequeue.go

This commit refactors ingest so that we also ack messages that we cannot
process. This ensures that the messages that fail don't get stuck at the
top of the queue. Messages that fail are not cleaned up, so they _will_
get re-queued eventually. This helps un-block processing of messages.

dequeue: acknowledge messages that fail to process

---

cmd/ingest/main.go
config/config.go
config/plugin.go

This commit enhances the metrics exposed by ingest so that storages will
have "plugin" label documenting what plugin they originated from. This
makes it nice to filter for storage errors by plugin kind.

config: explose storage plugin in metric label

---

cmd/ingest/main.go
cmd/ingest/main_test.go
config/config.go
config/config_test.go
go.mod

This PR makes it possible to specify multiple plugin paths. The first
plugin found will take precedence over plugins specified later.

cmd/ingest/main_test.go: allow multiple plugin paths

---

cmd/ingest/main.go
config/config.go
dequeue/dequeue.go
dequeue/dequeue_test.go
go.mod

Add a Concurrency option to every workflow with default to BatchSize.
Each batch will be worked on by max <Concurrency> go routines.

Work on batch concurrently

---

README.md
cmd/ingest/main_test.go
plugin/cmd.go
plugin/noop.go
plugin/plugin.go
plugins/noop/main.go
plugins/s3/main.go

This commit cleans up some of the identifiers that do not need to be
exported, standardizes the receiver names in methods, and cleans up the
README.

*: cleanup exported identifiers

---

cmd/ingest/main.go
cmd/ingest/main_test.go
queue/queue.go

Allow configuring the replica count of the ingest stream.

NATS stream replicas

---

cmd/ingest/main.go
cmd/ingest/main_test.go
queue/queue.go

Allow to configure the ingest jet stream with a maximum amount of
allowed messages flag.

jet stream maximum messages

---

cmd/ingest/main.go

Right now, the metrics concerning the dequeuer include labels for the
workflow and the destination but not the source. We can naturally infer
the source from the workflow name, but it's nice to have this in one
place in the metrics to help us easily tell what documents may be
failing to copy without needing to refer to the configuration.

observability: label dequeuer metrics with source

---

dequeue/dequeue.go
enqueue/enqueue.go
queue/subscription.go

- stop increasing the queue errors counter if the context deadline
exceeded. This just means that no new items were in the queue. No
error (tbd)
- stop logging "attempting to get next item from nexter, but log how
many items were fetched from the nexter

Logging and Metrics

---

cmd/ingest/main.go
storage/storage.go

Currently, the multi-storage implementation is unused, which means that
workflows with multiple destinations _cannot_ enable cleanup or else
files may be deleted in the source before every storage has had a chance
to upload it.
To work around this limitation, let's re-enable the use of
storage.MultiStorage. Note: although the consumer the name and number of
consumers has changed, elements do not need to be re-queued. This
convenience is enabled by the fact that each consumer has its own view
of the stream for the workflow. Old consumers suffixed with
`__<destination>` will need to be manually deleted from NATS.

storage: use multi-storage

---

cmd/ingest/main.go
config/config_test.go

Currently, metrics are labeled with `plugin="unknown"` because we are
failing a type assertion, which makes it hard to debug which plugin is
causing errors. This commit fixes the assertion and adds a test. We
should consider using a `SourceTyper` and `DestinationTyper` interface
rather than structs/structpointers.

metrics: fix plugin label

---

cmd/ingest/main.go
cmd/ingest/main_test.go
config/config.go
config/config_test.go
plugins/s3/main.go

Sometimes one workflow will be misconfigured, or have some runtime
issue, e.g. when Google Drive permissions are broken, which prevents the
entire ingest binary from starting. This is not always desirable, as
sometimes it is better for some ingestion to work rather than no
ingestion. This commit adds a flag to the binary that allows
misconfigured workflows to be skipped rather than causing the
application to exit with a failure. Whenever workflows are skipped, a
newly added metric is incremented, allowing administrators to alert on
ingest configuration errors rather than blindly running ingest without
realizing that a workflow is not running. This new mode of skipping
failed workflows is disabled by default.

config: allow skipping failed workflows

---

codec.go
codec_test.go
dequeue/dequeue_test.go
enqueue/enqueue_test.go
plugin/noop.go
plugin/plugin_test.go
plugins/s3/main.go
storage/s3/s3_test.go

The new field can be used by the individual plugins to pass meta data
form the enqueuer to the dequeuer, or even cross plugins.

codec: add meta field

---

plugin/manager.go

We were overriding metrics in a racy way.

plugin/manager.go: fix metrics gathering

---

config/config.go
storage/multi/multi.go
storage/multi/multi_test.go
storage/storage.go

Right now, if one of the storages backing a multi-storage returns an
error, the multi-storage still waits for all other storages to finish
responding before returning an error. This is wasteful, since we already
know that the final response of the stat call will be an error. This
commit changes this behavior so that all in-flight stats are canceled
as soon as one error is received.

multi-storage: fail fast in during stat

---

config/config.go
plugin/manager_test.go

Right now, some metrics related to plugins use the `type` label to mark
the plugin type and some metrics use the `plugin` label. This commit
unifies the metrics.

config: make plugin metrics use consistent labels

---

plugins/drive/main.go
storage/drive/drive.go

Currently, the Google Drive panic panics on startup because the find
method which requires a counter to be incremented, is called before the
counter is initialized.
This commit fixes this issue as well as fixes an issue where the
registry was never passed to the plugin, meaning the and metrics would
never actually be registered.

plugins/drive: fix panic on startup

---

config/config.go
plugin/manager.go

We reuse plugins across workflows. Putting a workflow label on a
plugin's metrics does not make sense and is confusing when a plugin is
used in more than one workflow.

Remove the workflow label from plugin

---

plugin/cmd.go
plugin/plugin.go
plugin/rpc.go
plugins/drive/main.go
plugins/noop/main.go
plugins/s3/main.go

When starting the plugin server, allow the developer to set the
Registerer and the logger with an Option. This way plugins can use that
defined logger in there own manner. Before it was not possible to write
custom log messages.

plugin: use options to set logger

---

config/config.go
config/config_test.go

Use environment variables in the configuration file with
`os.ExpandEnv`. Strings like `$VAR` or `${VAR}` will be replaced by the
corresponding environment variables.

config/: expand environment variables in config
